-   id: prettier
    name: prettier
    description: ''
    entry: pre-commit-prettier --write --ignore-unknown --experimental-cli --no-cache
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["prettier@3.6.2"]
    minimum_pre_commit_version: '0'
